# Generated by Django 4.0.1 on 2022-01-14 19:07
import datetime as dt

from django.db import migrations


def inserting(apps, schema_editor):
    Homework = apps.get_model('base', 'Homework')
    Student = apps.get_model('base', 'Student')
    Teacher = apps.get_model('base', 'Teacher')
    HomeworkResult = apps.get_model('base', 'HomeworkResult')

    hw = Homework(text='write an essay', deadline=dt.date(2022, 2, 1))
    student = Student(first_name='Andrey', last_name='Petrov')
    teacher = Teacher(first_name='Alex', last_name='Popov')
    hwresult = HomeworkResult(author=student, homework=hw, solution='essay')

    [obj.save() for obj in (hw, student, teacher, hwresult)]


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(inserting)
    ]
